/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Daniel
 */
public class ShowMap extends javax.swing.JPanel {

    /**
     * Creates new form ShowMap
     */
    public ShowMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        weekdayButton = new javax.swing.JButton();
        weekendButton = new javax.swing.JButton();
        mapLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Map");

        weekdayButton.setText("Weekday");
        weekdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekdayButtonActionPerformed(evt);
            }
        });

        weekendButton.setText("Weekend");
        weekendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(153, 153, 153)
                        .addComponent(weekdayButton)
                        .addGap(65, 65, 65)
                        .addComponent(weekendButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weekdayButton)
                        .addComponent(weekendButton)))
                .addGap(26, 26, 26)
                .addComponent(mapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void weekdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekdayButtonActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("system-map-weekday.png");
        mapLabel.setIcon(icon);
    }//GEN-LAST:event_weekdayButtonActionPerformed

    private void weekendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekendButtonActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("system-map-sunday.png"); 
        mapLabel.setIcon(icon); 
    }//GEN-LAST:event_weekendButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JButton weekdayButton;
    private javax.swing.JButton weekendButton;
    // End of variables declaration//GEN-END:variables
}
