/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author TinThuZarAye
 */
public class SpecialSchedule extends javax.swing.JPanel {

    /**
     * Creates new form SpecialSchedule
     */
    public SpecialSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        weekdaysButton = new javax.swing.JButton();
        weekendButton = new javax.swing.JButton();
        specialHolidayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("Schedules");

        weekdaysButton.setForeground(new java.awt.Color(0, 153, 102));
        weekdaysButton.setText("Weekdays");
        weekdaysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekdaysButtonActionPerformed(evt);
            }
        });

        weekendButton.setForeground(new java.awt.Color(0, 153, 102));
        weekendButton.setText("Weekend");
        weekendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekendButtonActionPerformed(evt);
            }
        });

        specialHolidayButton.setForeground(new java.awt.Color(204, 0, 51));
        specialHolidayButton.setText("SpecialHoliday");
        specialHolidayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialHolidayButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(weekdaysButton)
                .addGap(31, 31, 31)
                .addComponent(weekendButton)
                .addGap(26, 26, 26)
                .addComponent(specialHolidayButton)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekdaysButton)
                    .addComponent(specialHolidayButton)
                    .addComponent(weekendButton))
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void weekendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekendButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.setFont(jTextArea1.getFont().deriveFont(Font.BOLD, 14f));
        jTextArea1.setForeground(Color.RED);
        jTextArea1.setText("The following routes are running in the Weekend: \n\n");
        jTextArea1.append("Antioch - SFO/Millbrae Line : 8am to 9pm \n\n");
        jTextArea1.append("Dublin/Pleasanton - Montgomery St/Daly City Line : 8am to 9pm\n\n");
        jTextArea1.append("Berryessa/North San Jose - Richmond Line : 8am to 9pm\n\n");
        jTextArea1.append("SFO - Millbrae Shuttle : 8am to 9pm\n\n");
        jTextArea1.append("Oakland International Airport (OAK) : 8am to 9pm");
    }//GEN-LAST:event_weekendButtonActionPerformed

    private void weekdaysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekdaysButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.setFont(jTextArea1.getFont().deriveFont(Font.BOLD, 14f));
        jTextArea1.setForeground(Color.RED);
        jTextArea1.setText("The following routes are running in the Weekday: \n\n");
        jTextArea1.append("Antioch - SFO/Millbrae Line : 5am to 9pm\n\n");
        jTextArea1.append("Dublin/Pleasanton - Daly City Line : 5am to 9pm \n\n");
        jTextArea1.append("Berryessa/North San Jose - Richmond Line : 5am to 9pm\n\n");
        jTextArea1.append("Richmond - Millbrae Line : 5am to 9pm\n\n");
        jTextArea1.append("SFO - Millbrae Shuttle : 5am to 9pm\n\n");
        jTextArea1.append("Oakland International Airport (OAK) : 5am to 9pm");
    
    }//GEN-LAST:event_weekdaysButtonActionPerformed

    private void specialHolidayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialHolidayButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.setFont(jTextArea1.getFont().deriveFont(Font.BOLD, 14f));
        jTextArea1.setForeground(Color.RED);
        jTextArea1.setText("Thankgiving Day: Date:\n ");
        jTextArea1.append("Date:  11/25/2021\n");
        jTextArea1.append("Schedule Type: Thursday\n\n");
        jTextArea1.append("Christmas Day \n");
        jTextArea1.append("Date: 12/25/2021\n");
        jTextArea1.append("Schedule Type: Saturday\n\n");
        jTextArea1.append("New Year Day: \n");
        jTextArea1.append("Date: 01/01/2022\n");
        jTextArea1.append("Schedule Type: Saturday\n\n");
        jTextArea1.append("Martin Luther King, Jr. Day: \n");
        jTextArea1.append("Date: 01/18/2021\n");
        jTextArea1.append("Schedule Type: Monday\n\n");
        jTextArea1.append("Presidents' Day\n");
        jTextArea1.append("Date: 02/15/2021\n");
        jTextArea1.append("Schedule Type: Monday\n\n");
        jTextArea1.append("Memorial Day: \n");
        jTextArea1.append("Date: 05/31/2021\n");
        jTextArea1.append("Schedule Type: Monday\n\n");
        jTextArea1.append("Independence Day: \n");
        jTextArea1.append("Date: 07/04/2021\n");
        jTextArea1.append("Schedule Type: Sunday\n\n");
        jTextArea1.append("Labor Day: \n");
        jTextArea1.append("Date: 09/06/2021\n");
        jTextArea1.append("Schedule Type: Monday");
    }//GEN-LAST:event_specialHolidayButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton specialHolidayButton;
    private javax.swing.JButton weekdaysButton;
    private javax.swing.JButton weekendButton;
    // End of variables declaration//GEN-END:variables
}
