/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import api.BartAPI; 
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.*; 

/**
 *
 * @author TinThuZarAye
 */
public class StationSchedule extends javax.swing.JPanel {

    /**
     * Creates new form StationSchedule
     */
    BartSchedule bartSchedule; 
    BartAPI bartAPI; 
    List<String> ls; 
    List<String> ls_name; 
    TicketPayment ticketPayment; 
    
    static List<String> info; 
    
    static String fST; 
    static String tST; 
    static String transitS; 
    static String tP; 
    static String tripT; 
    
    public StationSchedule() {
        initComponents();
        info = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        buyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        departureTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        arrivalTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ticketPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tripTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        transitStationTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        fromStation = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        toStation = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(788, 562));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Choose Station");

        checkButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        buyButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setText("Departure Time From Station");

        jLabel5.setText("Arrival Time To Station");

        arrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalTimeActionPerformed(evt);
            }
        });

        jLabel6.setText("Ticket Price");

        jLabel7.setText("Trip Time");

        jLabel8.setText("Transit Station");

        transitStationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transitStationTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tripTime, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(ticketPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(arrivalTime, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(departureTime, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(transitStationTextField))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transitStationTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tripTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fromStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Station", "12th St. Oakland City Center", "16th St. Mission", "19th St. Oakland", "24th St. Mission", "Antioch", "Ashby", "Balboa Park", "Bay Fair", "Berryessa/North San Jose", "Castro Valley", "Civic Center/UN Plaza", "Coliseum", "Colma", "Concord", "Daly City", "Downtown Berkeley", "Dublin/Pleasanton", "El Cerrito del Norte", "El Cerrito Plaza", "Embarcadero", "Fremont", "Fruitvale", "Glen Park", "Hayward", "Lafayette", "Lake Merritt", "MacArthur", "Millbrae", "Milpitas", "Montgomery St.", "North Berkeley", "North Concord/Martinez", "Oakland International Airport", "Orinda", "Pittsburg/Bay Point", "Pittsburg Center", "Pleasant Hill/Contra Costa Centre", "Powell St.", "Richmond", "Rockridge", "San Bruno", "San Francisco International Airport", "San Leandro", "South Hayward", "South San Francisco", "Union City", "Walnut Creek", "Warm Springs/South Fremont", "West Dublin/Pleasanton", "West Oakland" }));
        fromStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromStationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("From Station:");

        toStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Station ", "12th St. Oakland City Center", "16th St. Mission", "19th St. Oakland", "24th St. Mission", "Antioch", "Ashby", "Balboa Park", "Bay Fair", "Berryessa/North San Jose", "Castro Valley", "Civic Center/UN Plaza", "Coliseum", "Colma", "Concord", "Daly City", "Downtown Berkeley", "Dublin/Pleasanton", "El Cerrito del Norte", "El Cerrito Plaza", "Embarcadero", "Fremont", "Fruitvale", "Glen Park", "Hayward", "Lafayette", "Lake Merritt", "MacArthur", "Millbrae", "Milpitas", "Montgomery St.", "North Berkeley", "North Concord/Martinez", "Oakland International Airport", "Orinda", "Pittsburg/Bay Point", "Pittsburg Center", "Pleasant Hill/Contra Costa Centre", "Powell St.", "Richmond", "Rockridge", "San Bruno", "San Francisco International Airport", "San Leandro", "South Hayward", "South San Francisco", "Union City", "Walnut Creek", "Warm Springs/South Fremont", "West Dublin/Pleasanton", "West Oakland" }));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("To Station: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromStation, 0, 345, Short.MAX_VALUE)
                    .addComponent(toStation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(checkButton)
                        .addGap(38, 38, 38)
                        .addComponent(buyButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyButton)
                    .addComponent(checkButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void arrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalTimeActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
        //jTabbedPane1.setSelectedIndex(5);
        bartSchedule.ticketPaymentPanel(); 
        info.add(fST); 
        info.add(tST); 
        info.add(transitS); 
        info.add(tP); 
        info.add(tripT); 
        
        //ticketPayment.amount.setText("$");
        TicketPayment.price = tP; 
        TicketPayment.setPrice();
        System.out.println(tP); 
        System.out.println(info); 
        
    }//GEN-LAST:event_buyButtonActionPerformed

    private void fromStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromStationActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
          bartAPI.mapValue(); 
          

          String fromSta = bartAPI.map.get(fromStation.getSelectedItem().toString()); 
          String toSta = bartAPI.map.get(toStation.getSelectedItem().toString()); 
          String url = "http://api.bart.gov/api/sched.aspx?cmd=depart&orig=" + fromSta + "&dest=" + toSta +"&date=now&key=MW9S-E7SL-26DU-VV8V&b=2&a=2&l=1&json=y";
          //System.out.println(bartAPI.bartAPICalled(url)); 
          JSONObject obj = bartAPI.bartAPICalled(url); 
          
          //JSONArray jarray = obj.getJSONArray("trip"); 
          JSONObject obj1 = obj.getJSONObject("root");
          JSONObject obj2 = obj1.getJSONObject("schedule"); 
          JSONObject obj3 = obj2.getJSONObject("request"); 
          
          JSONArray jarray = obj3.getJSONArray("trip");
          JSONObject jObj  = jarray.getJSONObject(0);
          JSONObject jObj1 = jarray.getJSONObject(1); 
          JSONObject jObj2 = jarray.getJSONObject(2); 
          JSONObject jObj3 = jarray.getJSONObject(3); 
          
          ls = new ArrayList(); 
          ls_name = new ArrayList(); 
          
          JSONArray jsonArray = jObj.getJSONArray("leg");
          
          for(int i=0; i<jsonArray.length(); i++){
             
              JSONObject jsonObj = jsonArray.getJSONObject(i);
              ls.add(jsonObj.getString("@destination")); 
              
          }
          
          for(int i=0; i<ls.size(); i++){
            for(Map.Entry<String,String> entry : bartAPI.map.entrySet()){

                    if(ls.get(i).equals(entry.getValue()) && !ls.get(i).equals(toSta))
                        ls_name.add(entry.getKey()); 

            }
          }
          
          String transitStation = ""; 
          
          if(ls_name.size() != 0){
            for(String s : ls_name)
                transitStation += s + " "; 
          }
          else{
              transitStation = "No transit !"; 
          }
          
 
          this.fST = jObj.getString("@origTimeMin") + "  |  " + jObj1.getString("@origTimeMin") + "  |  " +
                     jObj2.getString("@origTimeMin") + "  |  " + jObj3.getString("@origTimeMin");
          this.departureTime.setText(this.fST); 
          //info.add(this.fST); 
          
          this.tST = jObj.getString("@destTimeMin") + "  |  " + jObj1.getString("@destTimeMin") + "  |  " +
                     jObj2.getString("@destTimeMin") + "  |  " + jObj3.getString("@destTimeMin");
          this.arrivalTime.setText(this.tST); 
          //info.add(this.tST); 
          
          this.transitS = transitStation;
          this.transitStationTextField.setText(this.transitS); 
          //info.add(this.transitS); 
          
          this.tP = "$ " + jObj.getString("@fare"); 
          this.ticketPrice.setText(this.tP);
          //info.add(this.tP); 
          
          this.tripT = jObj.getString("@tripTime"); 
          this.tripTime.setText(this.tripT);
          //info.add(this.tripT); 
          
    }//GEN-LAST:event_checkButtonActionPerformed

    private void transitStationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transitStationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transitStationTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalTime;
    private javax.swing.JButton buyButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JTextField departureTime;
    private javax.swing.JComboBox<String> fromStation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ticketPrice;
    private javax.swing.JComboBox<String> toStation;
    private javax.swing.JTextField transitStationTextField;
    private javax.swing.JTextField tripTime;
    // End of variables declaration//GEN-END:variables
}
