/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.net.HttpURLConnection;
import java.net.URL;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import org.json.JSONArray;
import org.json.JSONObject;
/**
 *
 * @author Timothy 
 */
public class StationElevators extends javax.swing.JPanel {
    
    HttpURLConnection conn;
    /**
     * Creates new form StationElevators
     */
    public StationElevators() {
        initComponents();
        
        StringBuilder result = new StringBuilder();
        
        String elevator_info = "https://api.bart.gov/api/bsa.aspx?cmd=elev&key=ZZ22-58T5-93RT-DWEI&json=y";
        try{

            URL url = new URL(elevator_info);

            conn = (HttpURLConnection) url.openConnection();
            InputStream in = new BufferedInputStream(conn.getInputStream());
            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            String line;
            while ((line = reader.readLine()) != null) {
                result.append(line);
            }
        }
        catch(IOException e){
        }
        finally {
                conn.disconnect();
        }
        

        jTextArea1.setText(result.toString());
        JSONObject obj_JSONObject = new JSONObject(result.toString());
        JSONObject obj_JSONObject1 = obj_JSONObject.getJSONObject("root");
        
        JSONArray obj_JSONArray1 = obj_JSONObject1.getJSONArray("bsa");
        System.out.println(obj_JSONArray1);
        
        JSONObject obj_JSONObject2 = obj_JSONArray1.getJSONObject(0);
        JSONObject obj_JSONObject3 = obj_JSONObject2.getJSONObject("description");
        
        System.out.println(obj_JSONObject1);
        String date = obj_JSONObject1.getString("date");
        String time = obj_JSONObject1.getString("time");
        String type = obj_JSONObject2.getString("type");
        String description = obj_JSONObject3.getString("#cdata-section");
        jTextArea1.setText("Date: " + date );
        jTextArea1.append("\n\nTime: " + time);
        jTextArea1.append("\n\nType: " + type);
        jTextArea1.append("\n\n" + description);
        jTextArea1.append("\n\n Note: To check if an elevator is in service before arriving at a station\n");
        jTextArea1.append("please call 510-834-LIFT (510-834-5438) or 888-2-ELEVAT (888-235-3828)");
        jTextArea1.setFont(jTextArea1.getFont().deriveFont(Font.BOLD, 12f));
        jTextArea1.setForeground(Color.BLUE);
        //System.out.print("Date: " + obj_JSONObject1.getString("date"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Station Elevators Information");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
